version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bankflow-postgres
    environment:
      POSTGRES_DB: bankflow
      POSTGRES_USER: bankflow
      POSTGRES_PASSWORD: bankflow123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bankflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bank.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bankflow-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankflow
      SPRING_DATASOURCE_USERNAME: bankflow
      SPRING_DATASOURCE_PASSWORD: bankflow123
      JWT_SECRET: minha-chave-super-secreta-para-jwt-bankflow-2024-nao-usar-em-producao
      JWT_EXPIRATION: 900000
      JWT_REFRESH_EXPIRATION: 604800000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bankflow-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
